### ISSUE TITLE
Feature Mention in "This Does Not Compute" - Retro Mac Build Using Your Project

### ISSUE THREAD

**Issue by dariuszsikorski** [TheRealBolle/SE30#3]
Hi there,

I wanted to let you know that a video titled "I built a retro Mac from BRAND NEW parts!" was recently published on the This Does Not Compute YouTube channel: [Watch it here](https://www.youtube.com/watch?v=zc3sPoqOFG8)

The video showcases your project in action! The creator rebuilt a retro Mac using the design you developed for the motherboard. I couldn't find any contact info or email to reach you directly, so I thought I'd drop this as a GitHub issue in case you're interested. Of course, feel free to close it or do whatever you see fit – maybe even mention it in the README as a cool project highlight.

There's also a brief mention of a minor error with one of the trace connections at 14:02 in the video. It might be worth looking into and updating the motherboard schematic.

Overall, this is a very exciting project, and I’m thrilled to see your work getting such attention. Kudos to the creator for taking the time to recreate the motherboard based on your work!

Best regards!

**Comment by TheRealBolle** [comment]
This has already been corrected with R4

**Comment by reinauer** [comment]
Is this present on all versions prior to R4? Is there documentation on the rework other than the video?
